-- Schema Migration for a production-ready RAG system
-- Enables vector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Drop old objects if they exist to start fresh
DROP TABLE IF EXISTS public.clinical_notes_embeddings CASCADE;
DROP VIEW IF EXISTS public.clinical_notes_summary;
DROP FUNCTION IF EXISTS public.match_clinical_notes;

-- Create the new clinical_notes_embeddings table
CREATE TABLE public.clinical_notes_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id TEXT NOT NULL,
  note_id TEXT NOT NULL,
  chunk_index INTEGER NOT NULL DEFAULT 0,
  content TEXT NOT NULL,
  embedding vector(768), -- For Google text-embedding-004 (768 dimensions)
  metadata JSONB, -- Store note_date, note_type, provider, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for standard filtering
CREATE INDEX idx_clinical_notes_embeddings_patient_id ON public.clinical_notes_embeddings(patient_id);
CREATE INDEX idx_clinical_notes_embeddings_note_id ON public.clinical_notes_embeddings(note_id);
CREATE INDEX idx_clinical_notes_embeddings_metadata_gin ON public.clinical_notes_embeddings USING gin(metadata);

-- Add unique constraint on note_id + chunk_index to prevent duplicates
ALTER TABLE public.clinical_notes_embeddings
ADD CONSTRAINT unique_note_chunk UNIQUE (note_id, chunk_index);

-- ⭐️ IMPROVEMENT 1: Add HNSW index for fast vector search
-- This is crucial for RAG performance.
-- Uses cosine similarity, which is standard for Google's embedding models.
CREATE INDEX idx_clinical_notes_embeddings_hnsw ON public.clinical_notes_embeddings
USING hnsw (embedding vector_cosine_ops);

-- Create a function for automatic updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER handle_clinical_notes_embeddings_updated_at
BEFORE UPDATE ON public.clinical_notes_embeddings
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE public.clinical_notes_embeddings ENABLE ROW LEVEL SECURITY;

-- ⭐️ IMPROVEMENT 2: Add patient-centric RLS policies
-- This policy allows full access to internal system roles.
CREATE POLICY "Allow service_role full access"
ON public.clinical_notes_embeddings
FOR ALL USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- This policy allows an authenticated user to read *only* their own patient's notes.
-- It assumes you have a custom claim 'patient_id' in your JWT.
-- If not, you'll need to join against a 'profiles' table.
CREATE POLICY "Allow authenticated users to read their patient's notes"
ON public.clinical_notes_embeddings
FOR SELECT USING (
  auth.role() = 'authenticated' AND
  (metadata->>'patient_id') = (auth.jwt()->>'patient_id')
);

-- Grant permissions to roles
GRANT ALL ON public.clinical_notes_embeddings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.clinical_notes_embeddings TO authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- ------------------------------------------------------------------
-- ⭐️ IMPROVEMENT 3: Create a similarity search function
-- ------------------------------------------------------------------
-- This function encapsulates your RAG query logic.
CREATE OR REPLACE FUNCTION public.match_clinical_notes (
  query_patient_id TEXT,
  query_embedding vector(768),
  match_threshold FLOAT,
  match_count INT
)
RETURNS TABLE (
  id BIGINT,
  content TEXT,
  metadata JSONB,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $
BEGIN
  RETURN QUERY
  SELECT
    cne.id,
    cne.content,
    cne.metadata,
    1 - (cne.embedding <=> query_embedding) AS similarity
  FROM
    public.clinical_notes_embeddings AS cne
  WHERE
    -- Filter by patient_id FIRST for security and performance
    cne.patient_id = query_patient_id
    AND 1 - (cne.embedding <=> query_embedding) > match_threshold
  ORDER BY
    similarity DESC
    -- 💡 You could also order by (metadata->>'note_date') DESC
  LIMIT match_count;
END;
$;